import { Product } from "./types/product";

export const sampleProducts: Product[] = [
  {
    _id: "1",
    name: "Poster",
    slug: "Poster1",
    image: "../images/1.jpg",
    category: "Poster",
    price: 10,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "2",
    name: "Poster",
    slug: "Poster2",
    image: "../images/2.jpg",
    category: "Poster2",
    price: 14,
    countInStock: 0,
    description: "Poster2",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "3",
    name: "Poster3",
    slug: "Poster3",
    image: "../images/3.jpg",
    category: "Poster3",
    price: 15,
    countInStock: 12,
    description: "Poster3",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "4",
    name: "Poster4",
    slug: "Poster4",
    image: "../images/4.jpg",
    category: "Poster",
    price: 20,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "5",
    name: "Poster5",
    slug: "Poster5",
    image: "../images/5.jpg",
    category: "Poster",
    price: 30,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "6",
    name: "Poster6",
    slug: "Poster6",
    image: "../images/6.jpg",
    category: "Poster",
    price: 12,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "7",
    name: "Poster7",
    slug: "Poster7",
    image: "../images/7.jpg",
    category: "Poster",
    price: 5,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "8",
    name: "Poster8",
    slug: "Poster8",
    image: "../images/8.jpg",
    category: "Poster",
    price: 10,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "9",
    name: "Poster9",
    slug: "Poster9",
    image: "../images/9.jpg",
    category: "Poster",
    price: 50,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "10",
    name: "Poster10",
    slug: "Poster10",
    image: "../images/10.jpg",
    category: "Poster",
    price: 20,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "11",
    name: "Poster11",
    slug: "Poster11",
    image: "../images/11.jpg",
    category: "Poster",
    price: 35,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
  {
    _id: "4",
    name: "Poster12",
    slug: "Poster12",
    image: "../images/12.jpg",
    category: "Poster",
    price: 36,
    countInStock: 12,
    description: "Poster",
    rating: 4.5,
    numReviews: 20,
  },
];
